teleop_node:
  ros__parameters:
    require_enable_button: true
    enable_button: 3

    inverted_reverse: true

    axis_linear:
      x: 1
    axis_angular:
      yaw: 0

    scale_linear:
      x: 0.5
    scale_angular:
      yaw: 0.5

    enable_turbo_button: 5 
    scale_linear_turbo:
      x: 2.0 
    scale_angular_turbo:
      yaw: 1.0